### ISSUE TITLE
integrate basket

### ISSUE THREAD

**Issue by johngruen** [mozilla/idea-town#15]

**Comment by pdehaan** [comment]
Fun tales of Basket API at https://github.com/mozilla/fxa-content-server/issues/2873 and https://github.com/mozilla/fxa-content-server/issues/2870.

**TL;DR:** It seems that Basket takes a 20m downtime every night, ... just because.

**Comment by johngruen** [comment]
@pdehaan the status of this issue is up in the air. I'll provide more details tomorrow after nick and i meet with engagement.

**Comment by pdehaan** [comment]
@johngruen Thanks. If you have a chance to ask them why the Basket API goes offline for 20m/day for maintenance, I'd be interested in that story.

**Comment by johngruen** [comment]
Closing this for now, because basket === basket
