### ISSUE TITLE
Audit the bower.json file

### ISSUE THREAD

**Issue by pdehaan** [mozilla/idea-town#17]
The [bower.json](https://github.com/mozilla/idea-town/blob/master/bower.json) file looks like it has some old repo names and inconsistencies with license (vs package.json).

Also make sure all the dependencies are used (I didn't see any references to "slick" in the code, but I did a really sloppy/quick search).

**Comment by meandavejustice** [comment]
It appears no client-side js has been written at all yet, so jquery and slick.js could be removed. Also `normalize.css` and `mozilla-tabzilla` could both be installed via npm and copied over to the public dir with gulp or an npm-script. This would remove the bower dependency entirely.
