### ISSUE TITLE
Add GA

### ISSUE THREAD

**Issue by johngruen** [mozilla/idea-town#22]

**Comment by 6a68** [comment]
Waiting on this bug to get our tracking code: https://bugzilla.mozilla.org/show_bug.cgi?id=1191017

**Comment by 6a68** [comment]
Background info: tracking code is `UA-49796218-34`. It's currently whitelisted to our dev and prod URLs. Once I know the stage URL, I'll update the bugzilla bug and get it whitelisted, too.

I'll submit a PR to add the snippet to the index page.
