### ISSUE TITLE
Add Helmet middleware to Express server

### ISSUE THREAD

**Issue by pdehaan** [mozilla/idea-town#32]
From the department of premature micro-optimizations...

Once the **express** PR lands (#24), should we add the glorious [**helmet**](https://www.npmjs.com/package/helmet) to give us some basic security bits? IIRC, **hapi** did some/most of the magically for us, but we're venturing back in time to the scary corners of **express@3**.

**Comment by 6a68** [comment]
@pdehaan yeah, we definitely care about security - this will be running on a subdomain of firefox.com or mozilla.com or something, and might get a lot of traffic. Common sense precautions do matter here.

**Comment by 6a68** [comment]
Sorry, wrong button
