### ISSUE TITLE
Send confirmation email

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/idea-town#36]
After writing successfully to Dynamo

**Comment by 6a68** [comment]
@johngruen Do we have any email templates for idea town, or that we could reuse?

**Comment by 6a68** [comment]
If picking an email provider is a blocker, we can also just say something like, "Thanks for signing up! We'll be in touch eventually" on the signup page.

**Comment by johngruen** [comment]
@6a68 we are meeting with email gatekeepers today. Nick also discovered an ancient Mail Chimp blog post talking about how Moz uses Mail Chimp, so we're still bugging legal as well. Whatever happens here, I'll be on the hook for it.

**Comment by nchapman** [comment]
Yeah we might just skip sending a confirmation email for now. I think this is going to make things more complicated than we need them to be.

**Comment by pdehaan** [comment]
This will be resolved by Basket/ExactTarget. Closing.
