### ISSUE TITLE
Client Side error/confirmation

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/idea-town#37]
We need to let the user know something once their info is submitted

**Comment by 6a68** [comment]
@johngruen do you have thoughts on wording for the success / failure messages?

Cases will probably include
- user signed up successfully, yay!
- email is malformed or there's no email at all
- server is down & the user has to wait/try again
- (maybe) email already exists in DB (we may or may not wind up checking this)

**Comment by johngruen** [comment]
@6a68 @meandavejustice don't worry about styling these things up for now, just slap these strings in a div with a success or error class on each and I can do the rest. 

> user signed up successfully, yay!
Thank you! Keep an eye on your inbox. We'll invite you to try out Idea Town as soon as it's ready.
(also the input/submit should go away in this case)

> email is malformed or there's no email at all
Invalid email address. Try again.

> server is down & the user has to wait/try again
Oh dear, something went wrong there. Try again soon.

> (maybe) email already exists in DB (we may or may not wind up checking this
I don't think we should message to this, just show the success message and not rewrite the email to the DB...sort of seems like a minor privacy issue.

**Comment by johngruen** [comment]
#74
