### ISSUE TITLE
Server should gracefully handle uncaughtException, posix signals

### ISSUE THREAD

**Issue by 6a68** [mozilla/idea-town#39]

**Comment by meandavejustice** [comment]
@6a68 could you expand on this a bit?

**Comment by 6a68** [comment]
I'll do it

**Comment by 6a68** [comment]
There aren't really any resources to clean up, so I guess this isn't needed at all.

I was worried about manually closing in-flight dynamo requests created by the aws-sdk. Since it doesn't use keepalives, dcoates assures me that any file descriptors will be cleaned up by the OS on process exit, so we just don't worry about them.

Since we don't have any other open sockets, there doesn't seem to be any reason to intercept `'uncaughtException'`, `SIGTERM`, or `SIGINT`.

Building tiny things is weird ^_^
