### ISSUE TITLE
Get the domain name ideatown.firefox.com

### ISSUE THREAD

**Issue by 6a68** [mozilla/idea-town#45]
@nchapman is there a bugzilla bug for this yet?

**Comment by johngruen** [comment]
@6a68 @nchapman and I talked to Travis (the human, not the testing service) yesterday, and he confirmed that this is trivial. AFAIK, no bug required.

**Comment by nchapman** [comment]
> @6a68 @nchapman and I talked to Travis (the human, not the testing service) yesterday, and he confirmed that this is trivial. AFAIK, no bug required.

+1

**Comment by 6a68** [comment]
@nchapman Sounds like we can close this?

**Comment by 6a68** [comment]
I found a bugzilla bug that @mostlygeek opened to track ops work, including getting the name configured. Closing in favor of it: https://bugzilla.mozilla.org/show_bug.cgi?id=1192920
