### ISSUE TITLE
validate email before sending

### ISSUE THREAD

**Issue by 6a68** [mozilla/idea-town#46]
We can just use the FF built-in validation. It's lenient (allows `user@localhost`) but RFC compliant.

https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5/Constraint_validation

**Comment by johngruen** [comment]
There's also a basic validation scheme on FxA that we could steal. 

from: https://github.com/mozilla/fxa-content-server/blob/master/app/scripts/lib/validate.js#L21
```
   isEmailValid: function (email) {
      if (typeof email !== 'string') {
        return false;
      }

      var parts = email.split('@');

      var localLength = parts[0] && parts[0].length;
      var domainLength = parts[1] && parts[1].length;

      // Original regexp from:
      //  http://blog.gerv.net/2011/05/html5_email_address_regexp/
      // Modified to remove the length checks, which are done later.
      // IETF spec: http://tools.ietf.org/html/rfc5321#section-4.5.3.1.1
      // NOTE: this does *NOT* allow internationalized domain names.
      return (/^[\w.!#$%&'*+\-\/=?\^`{|}~]+@[a-z\d][a-z\d\-]*(?:\.[a-z\d][a-z\d\-]*)*$/i).test(email) &&
             // total email allwed to be 256 bytes long
             email.length <= 256 &&
             // local side only allowed to be 64 bytes long
             1 <= localLength && localLength <= 64 &&
             // domain side allowed to be up to 255 bytes long which
             // doesn't make much sense unless the local side has 0 length;
             1 <= domainLength && domainLength <= 255;
    },
```

**Comment by 6a68** [comment]
@johngruen great idea! these people should hopefully be signing up for fxa eventually, might as well reuse that code

**Comment by 6a68** [comment]
I do feel weird about copy-pasting that function, though. Maybe there's something comparable on npm we can use, or just publish their validation file to npm

**Comment by 6a68** [comment]
maybe we can use https://github.com/Sembiance/email-validator instead, seems to cover pretty much the same ground

**Comment by johngruen** [comment]
@6a68 I guess i don't feel totally weird about it. I mean, this thing is throw-away anyway. I've used it on other projects and given a hat tip to FxA

**Comment by pdehaan** [comment]
I vote for https://www.npmjs.com/package/isemail (which is what they use in Joi).
For some reason the GitHub link is broken, so I'm not sure of the repo.

**Comment by meandavejustice** [comment]
Couldn't we get away with just html5 validation? http://davidwalsh.name/html5-email
We could still use the regex from the fxa function above
