### ISSUE TITLE
Gulp init should clean out the public/ directory before writing stuff

### ISSUE THREAD

**Issue by pdehaan** [mozilla/idea-town#59]
Maybe.
I have a dirty public/ dir from a previous PR and noticed that my l20n files are still lingering, despite running `gulp init` a few times.

Not sure if **rimraf**ing that directory when calling `gulp init` will cause any issues w/ @johngruen's lovely `gulp watch` stuff, so we'll need to test for that.

nit: On that note, should it be called `gulp init` or `gulp build`. Calling it `init` always makes my mind think I just need to `npm install`, call `init` and never need to run it again. But now I'm getting lost in the weeds of task naming and am starting to loathe myself just a little bit more.

**Comment by johngruen** [comment]
fixed by #58, 

nb. gulp-rimraf seems to be deprecated in favor of del (https://github.com/gulpjs/gulp/blob/master/docs/recipes/delete-files-folder.md)
