### ISSUE TITLE
Is the splash site "coming soon-y" enough

### ISSUE THREAD

**Issue by johngruen** [mozilla/idea-town#63]
Do you guys think this site conveys that the product isn't ready quickly enough? Should there be a coming soon banner somewhere?

**Comment by johngruen** [comment]
Answer from marketing is resoundingly 'no'...i'll pr in a new string.

**Comment by pdehaan** [comment]
@johngruen Is this fixed by #76?

**Comment by johngruen** [comment]
@pdehaan Yes!
