### ISSUE TITLE
Handle bundle zipping in Gulp task?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/idea-town#66]
Not sure what this npm script `"bundle": "zip -r ../bundle.zip ./* ./.*",` thing is for, but it may make sense to make it a bit more cross-PC compatible and use Gulp. Maybe something like **gulp-zip** and:

```js
gulp.task('bundle', function () {
  return gulp.src(['**', '.*', '!.git', '!**/.DS_Store', '!bundle.zip'])
    .pipe(zip('bundle.zip'))
    .pipe(gulp.dest('.'));
});
```

This seems to make a 30MB ZIP (~75MB unzipped) which I assume gets deployed to beanstalk or something, but not sure if we need all the folders or if we can do a smaller subset of files.

**Comment by meandavejustice** [comment]
Locally I have been rming dev deps and some other things and zipping up before deploying to beanstalk. I would love to write a task to automate this stuff.

**Comment by pdehaan** [comment]
@meandavejustice Does EBS need *ALL* the files, or just some folders?
For example, can we only ZIP the following:
- [ ] app_config.json
- [ ] iam_policy.json
- [ ] node_modules/
- [ ] public/
- [ ] routes/
- [ ] src/
- [ ] views/
- [ ] server.js

**Comment by meandavejustice** [comment]
The selected files are needed, and all of the app's deps in node_modules(basically everything but all the gulp stuff)

**Comment by pdehaan** [comment]
Yeah, I just did an `rm -rf node_modules && npm i --production` and then realized that my devDeps weren't installed, so I can no longer use `gulp bundle` since I don't have **gulp** or **gulp-zip** installed.

**Comment by meandavejustice** [comment]
right, so within bundle we can just specify which directories from `node_modules` to include in the zip. We can get these from `Object.keys(require('./package.json').dependencies)`

**Comment by meandavejustice** [comment]
This is no longer necessary now that we are pushing directly to eb
