### ISSUE TITLE
monolithic repo or many repos?

### ISSUE THREAD

**Issue by 6a68** [mozilla/idea-town#67]

**Comment by meandavejustice** [comment]
:+1: for many repos, packaged as node_modules when appropriate. We can always install from npm with the `user/repo` syntax without actually publishing to npm.

**Comment by 6a68** [comment]
@meandavejustice we're fine to push everything we do to npm, mozilla works in the open :-)

I owe this bug some background info and pro/con breakdown

**Comment by 6a68** [comment]
We discussed this in the engineering meeting today; sounds like we'll go with multiple repos. Closing.
