### ISSUE TITLE
Animation Ideas

### ISSUE THREAD

**Issue by meandavejustice** [mozilla/idea-town#68]
* rope physics for the crane http://codepen.io/dissimulate/pen/fhjvk

**Comment by 6a68** [comment]
@johngruen are you planning to spec out interactions / animations here, or should we wing it?

**Comment by johngruen** [comment]
@meandavejustice @6a68 this is a little vague? do you mean for the email submission link?

**Comment by 6a68** [comment]
@johngruen nope, for the whimsical animations in the hero image at the top

**Comment by johngruen** [comment]
@meandavejustice @6a68 no winging it with the logo. Don't think we need anything animated for the splash site, but let's use this to drop in interesting examples. I'd like to spec something out, but i think bryan will want the opportunity to iterate further on the logo before we move on this.

**Comment by johngruen** [comment]
Wontfix...lets file this in specific terms down the road when we have time
