### ISSUE TITLE
form interaction polish

### ISSUE THREAD

**Issue by 6a68** [mozilla/idea-town#69]
@johngruen We can use this bug to record form interaction input that I was talking about in channel.

- how do we show email validation on the client? I was thinking red/green outline around the input when it's non-empty
- do we disable the button / show a spinner-ish image while the xhr is in flight? how do you want to do that?
- I think you mentioned just putting a node in the DOM for the error/success messages, and you'd style it. Do you want to do that for just that element, or spec that out and devs can do it all, or just take this bug and handle the finer details of all the interactions yourself?

**Comment by johngruen** [comment]
I'll spec this stuff out...already added success and error messages and styles with my UI pull request: https://github.com/mozilla/idea-town/blob/master/views/index.jade#L15

**Comment by johngruen** [comment]
#75
