### ISSUE TITLE
Firefox persists disabled submit buttons across page refreshes

### ISSUE THREAD

**Issue by johngruen** [mozilla/idea-town#79]
@meandavejustice as far as i can tell, Firefox is (for whatever reason) caching the state (disabled/enabled) of the submit button after successive page refreshes. Adding `submitBtnEl.disabled = false;` to line 13 of main.js seems to resolve this problem, but maybe there's something else going on. 

Cannot repro in any other browser.

**Comment by meandavejustice** [comment]
It is considered a feature in Firefox http://stackoverflow.com/questions/5985839/bug-with-firefox-disabled-attribute-of-input-not-resetting-when-refreshing

**Comment by meandavejustice** [comment]
I'll fix this in a pr in about 2 minutes

**Comment by johngruen** [comment]
Haha.  Thanks man!
