### ISSUE TITLE
Footer links not aligned on mobile

### ISSUE THREAD

**Issue by johngruen** [mozilla/idea-town#86]

**Comment by pdehaan** [comment]
![idea_town_and_idea_town](https://cloud.githubusercontent.com/assets/557895/9209363/f9432f88-402a-11e5-95e7-7078455a3bf0.png)

**Comment by 6a68** [comment]
Pulling into milestone 1, since we've got an open PR to fix this bug, and it's worth fixing.

**Comment by 6a68** [comment]
Fixed by #95
